### ISSUE TITLE
Instructions for in-game GM's

### ISSUE THREAD

**Issue by Baralta23** [omni-wow/Deathwing#3]
There are a couple things that need to be done, if you would like to work together or separate please talk with each other :)

-Place all justice vendors at each starting location A,H.
-Place mount vendors and riding trainers at each starting location A,H.
-Put weapons for each class into one of the justice vendors A,H.
-If the trainers DO NOT teach the classes ALL the training at the start, please place ALL class trainers A,H.

This thread is subject to be modified in the future in the case I've forgetting something.

Thanks, admin.

A=Alliance   H=Horde

**Comment by Daelmaron** [comment]
Don't have much I can do today, later this evening I think I might have about an hour that I can work on some of this, though I'll need to refamiliarize myself with everything and finish getting myself set up first.

**Comment by Baralta23** [comment]
https://www.reaper-x.com/2009/01/01/trinity-core-gm-commands/ this will help with command reference. If you have any questions about anything ask myself or Kitty.

**Comment by Daelmaron** [comment]
sounds good.

**Comment by Daelmaron** [comment]
are the vendors and trainers right now the most important thing in game?

**Comment by Daelmaron** [comment]
sounds good, the reference will be useful. I'll have to get it in once I get everything set up again.
