### ISSUE TITLE
The second part of tol barad is closed

### ISSUE THREAD

**Issue by Kanjii** [omni-wow/Deathwing#4]
Im miku, and ive doing dailies in tb recently but i realized that the door to the second part of tb is closed, it should be open cause there are more daily quests there

**Comment by Anthonhed** [comment]
Please include a picture

**Comment by Kanjii** [comment]
![wowscrnshot_122417_172302](https://user-images.githubusercontent.com/28495575/34329267-95a9a5b0-e8cf-11e7-89a8-baa11abd2b54.jpg)

here is the first door of the second part of tb that is closed

![wowscrnshot_122417_172331](https://user-images.githubusercontent.com/28495575/34329270-bc9a1344-e8cf-11e7-8309-a28dbb228f7d.jpg)

and this is the 2nd door of tb that is also closed, in case you wonder how i reached there, i used my ability called heroic leap, but i cant go through the second door, the doors should be open cause there are more daily quests in there
